# Generated by Django 4.1.4 on 2022-12-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('cod_especialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='código de la especialidad')),
                ('descripcion_especialidad', models.CharField(max_length=40, verbose_name='descripción de la especialidad')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
                'db_table': 'especialidad',
                'ordering': ['cod_especialidad'],
            },
        ),
        migrations.CreateModel(
            name='MotivoDeConsulta',
            fields=[
                ('cod_motivo', models.AutoField(primary_key=True, serialize=False, verbose_name='código del motivo de consulta')),
                ('descripcion_motivo', models.CharField(max_length=35, verbose_name='descripción del motivo de consulta')),
            ],
            options={
                'verbose_name': 'motivo de consulta',
                'verbose_name_plural': 'motivos de consulta',
                'db_table': 'motivo_de_consulta',
                'ordering': ['cod_motivo'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('cod_nacionalidad', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='código de la nacionalidad')),
                ('descripcion_nacionalidad', models.CharField(max_length=10, verbose_name='descripción de la nacionalidad')),
            ],
            options={
                'verbose_name': 'nacionalidad',
                'verbose_name_plural': 'nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['-cod_nacionalidad'],
            },
        ),
        migrations.CreateModel(
            name='NecesidadEspecial',
            fields=[
                ('cod_necesidad_especial', models.AutoField(primary_key=True, serialize=False, verbose_name='código de la necesidad especial')),
                ('descripcion_necesidad_especial', models.CharField(max_length=40, verbose_name='descripción de la necesidad especial')),
            ],
            options={
                'verbose_name': 'necesidad especial',
                'verbose_name_plural': 'necesidades especiales',
                'db_table': 'necesidad_especial',
                'ordering': ['cod_necesidad_especial'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('cod_sexo', models.AutoField(primary_key=True, serialize=False, verbose_name='código del sexo')),
                ('descripcion_sexo', models.CharField(max_length=10, verbose_name='descripción del sexo')),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
                'db_table': 'sexo',
                'ordering': ['cod_sexo'],
            },
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('cod_urgencia', models.AutoField(primary_key=True, serialize=False, verbose_name='código de la urgencia')),
                ('descripcion_urgencia', models.CharField(max_length=10, verbose_name='descripción de la urgencia')),
            ],
            options={
                'verbose_name': 'urgencia',
                'verbose_name_plural': 'urgencias',
                'db_table': 'urgencia',
                'ordering': ['cod_urgencia'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ci_doctor', models.IntegerField(primary_key=True, serialize=False, verbose_name='cédula')),
                ('nombres', models.CharField(max_length=64, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=64, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=128, null=True, verbose_name='dirección')),
                ('especialidad', models.ForeignKey(db_column='especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.especialidad', verbose_name='especialidad')),
                ('nacionalidad', models.ForeignKey(db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.nacionalidad', verbose_name='nacionalidad')),
                ('sexo', models.ForeignKey(db_column='sexo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.sexo', verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
                'db_table': 'doctores',
                'ordering': ['ci_doctor'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='cédula')),
                ('nombres', models.CharField(max_length=64, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=64, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=128, null=True, verbose_name='dirección')),
                ('nacionalidad', models.ForeignKey(db_column='nacionalidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.nacionalidad', verbose_name='nacionalidad')),
                ('necesidad_especial', models.ForeignKey(db_column='necesidad_especial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.necesidadespecial', verbose_name='necesidad especial')),
                ('sexo', models.ForeignKey(db_column='sexo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.sexo', verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ['ci_cliente'],
            },
        ),
    ]
