# Generated by Django 4.1.4 on 2022-12-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_sintoma_cita_cita_fecha y hora únicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('cod_diagnostico', models.AutoField(primary_key=True, serialize=False, verbose_name='código del diagnóstico')),
                ('descripcion_diagnostico', models.CharField(max_length=40, verbose_name='descripción del diagnóstico')),
            ],
            options={
                'verbose_name': 'diagnóstico',
                'verbose_name_plural': 'diagnósticos',
                'db_table': 'diagnostico',
                'ordering': ['cod_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='MotivoDeAusencia',
            fields=[
                ('cod_ausencia', models.AutoField(primary_key=True, serialize=False, verbose_name='código del motivo de ausencia')),
                ('descripcion_ausencia', models.CharField(max_length=40, verbose_name='descripción del motivo de ausencia')),
            ],
            options={
                'verbose_name': 'motivo de ausencia',
                'verbose_name_plural': 'motivos de ausencia',
                'db_table': 'motivo_de_ausencia',
                'ordering': ['cod_ausencia'],
            },
        ),
        migrations.CreateModel(
            name='SintomasCita',
            fields=[
                ('id_sintoma_cita', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del síntoma de la cita')),
                ('cita', models.ForeignKey(db_column='cita', on_delete=django.db.models.deletion.CASCADE, to='Citas.cita', verbose_name='cita')),
                ('sintoma', models.ForeignKey(db_column='sintoma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.sintoma', verbose_name='síntoma de la cita')),
            ],
            options={
                'verbose_name': 'síntoma de una cita',
                'verbose_name_plural': 'síntomas de una cita',
                'db_table': 'sintomas_cita',
                'ordering': ['cita', 'sintoma'],
            },
        ),
        migrations.AddConstraint(
            model_name='sintomascita',
            constraint=models.UniqueConstraint(fields=('cita', 'sintoma'), name='síntoma de una cita'),
        ),
    ]
