# Generated by Django 4.1.4 on 2022-12-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_diagnostico_motivodeausencia_sintomascita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('cod_area', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='código de área')),
                ('descripcion_area', models.CharField(max_length=15, verbose_name='descripción del código de área')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'db_table': 'area',
                'ordering': ['cod_area'],
            },
        ),
        migrations.CreateModel(
            name='CitaRechazada',
            fields=[
                ('cita', models.OneToOneField(db_column='cita', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Citas.cita', verbose_name='cita')),
            ],
            options={
                'verbose_name': 'cita rechazada',
                'verbose_name_plural': 'citas rechazadas',
                'db_table': 'citas_rechazadas',
                'ordering': ['cita'],
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('cod_dominio', models.AutoField(primary_key=True, serialize=False, verbose_name='código del dominio')),
                ('descripcion_dominio', models.CharField(max_length=67, verbose_name='descripción del dominio')),
            ],
            options={
                'verbose_name': 'dominio',
                'verbose_name_plural': 'dominios',
                'db_table': 'dominio',
                'ordering': ['cod_dominio'],
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('cod_parentesco', models.AutoField(primary_key=True, serialize=False, verbose_name='código del parentesco')),
                ('descripcion_parentesco', models.CharField(max_length=20, verbose_name='descripción del parentesco')),
            ],
            options={
                'verbose_name': 'parentesco',
                'verbose_name_plural': 'parentescos',
                'db_table': 'parentesco',
                'ordering': ['cod_parentesco'],
            },
        ),
        migrations.CreateModel(
            name='TelefonosDoctores',
            fields=[
                ('id_telefono_doctor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del teléfono del doctor')),
                ('numero_telefonico', models.CharField(max_length=7, verbose_name='número de teléfono')),
                ('area', models.ForeignKey(db_column='area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.area', verbose_name='código de área')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.CASCADE, to='Citas.doctor', verbose_name='doctor')),
            ],
            options={
                'verbose_name': 'teléfono de un doctor',
                'verbose_name_plural': 'teléfonos de los doctores',
                'db_table': 'telefonos_doctores',
                'ordering': ['doctor', 'area', 'numero_telefonico'],
            },
        ),
        migrations.CreateModel(
            name='TelefonosClientes',
            fields=[
                ('id_telefono_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del teléfono del cliente')),
                ('numero_telefonico', models.CharField(max_length=7, verbose_name='número de teléfono')),
                ('area', models.ForeignKey(db_column='area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.area', verbose_name='código de área')),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='Citas.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'teléfono de un cliente',
                'verbose_name_plural': 'teléfonos de los clientes',
                'db_table': 'telefonos_clientes',
                'ordering': ['cliente', 'area', 'numero_telefonico'],
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del familiar')),
                ('familiar', models.ForeignKey(db_column='familiar', on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='Citas.cliente', verbose_name='familiar')),
                ('nuevo_paciente', models.ForeignKey(db_column='nuevo_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_paciente', to='Citas.cliente', verbose_name='nuevo paciente')),
                ('parentesco', models.ForeignKey(db_column='parentesco', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.parentesco', verbose_name='parentesco')),
            ],
            options={
                'verbose_name': 'familiar',
                'verbose_name_plural': 'familiares',
                'db_table': 'familiares',
                'ordering': ['familiar', 'nuevo_paciente'],
            },
        ),
        migrations.CreateModel(
            name='EmailsDoctores',
            fields=[
                ('id_email_doctor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del email del doctor')),
                ('nombre_email', models.CharField(max_length=64, verbose_name='nombre del email')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.CASCADE, to='Citas.doctor', verbose_name='doctor')),
                ('dominio', models.ForeignKey(db_column='dominio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.dominio', verbose_name='dominio del correo')),
            ],
            options={
                'verbose_name': 'email de un doctor',
                'verbose_name_plural': 'emails de los doctores',
                'db_table': 'emails_doctores',
                'ordering': ['doctor', 'nombre_email', 'dominio'],
            },
        ),
        migrations.CreateModel(
            name='EmailsClientes',
            fields=[
                ('id_email_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del email del cliente')),
                ('nombre_email', models.CharField(max_length=64, verbose_name='nombre del email')),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='Citas.cliente', verbose_name='cliente')),
                ('dominio', models.ForeignKey(db_column='dominio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.dominio', verbose_name='dominio del correo')),
            ],
            options={
                'verbose_name': 'email de un cliente',
                'verbose_name_plural': 'emails de los clientes',
                'db_table': 'emails_clientes',
                'ordering': ['cliente', 'nombre_email', 'dominio'],
            },
        ),
        migrations.CreateModel(
            name='CitaAceptada',
            fields=[
                ('cita', models.OneToOneField(db_column='cita', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Citas.cita', verbose_name='cita')),
                ('cita_cumplida', models.BooleanField(blank=True, default=None, null=True, verbose_name='cita cumplida')),
                ('ausencia', models.ForeignKey(blank=True, db_column='ausencia', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.motivodeausencia', verbose_name='motivo de la ausencia')),
                ('diagnostico', models.ForeignKey(blank=True, db_column='diagnostico', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.diagnostico', verbose_name='diagnóstico del paciente')),
                ('doctor', models.ForeignKey(blank=True, db_column='doctor', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.doctor', verbose_name='cédula del doctor')),
            ],
            options={
                'verbose_name': 'cita aceptada',
                'verbose_name_plural': 'citas aceptadas',
                'db_table': 'citas_aceptadas',
                'ordering': ['cita'],
            },
        ),
        migrations.AddConstraint(
            model_name='telefonosdoctores',
            constraint=models.UniqueConstraint(fields=('area', 'numero_telefonico'), name='teléfono de un doctor'),
        ),
        migrations.AddConstraint(
            model_name='telefonosclientes',
            constraint=models.UniqueConstraint(fields=('area', 'numero_telefonico'), name='teléfono de un cliente'),
        ),
        migrations.AddConstraint(
            model_name='familiar',
            constraint=models.UniqueConstraint(fields=('nuevo_paciente', 'familiar'), name='parentesco único'),
        ),
        migrations.AddConstraint(
            model_name='emailsdoctores',
            constraint=models.UniqueConstraint(fields=('nombre_email', 'dominio'), name='email de un doctor'),
        ),
        migrations.AddConstraint(
            model_name='emailsclientes',
            constraint=models.UniqueConstraint(fields=('nombre_email', 'dominio'), name='email de un cliente'),
        ),
    ]
