# Generated by Django 4.1.4 on 2023-02-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_area_citarechazada_dominio_parentesco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor_cita',
            field=models.ForeignKey(db_column='doctor_cita', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Citas.doctor', verbose_name='doctor solicitado'),
        ),
    ]
