from django.urls import path

from Aplicaciones.Citas.views import *

urlpatterns = [
    path('', index, name='index'),
    path('servicios/odontologia-general', odontologiaGeneral, name='odontologiaGeneral'),
    path('servicios/limpieza-dental', limpiezaDental, name='limpiezaDental'),
    path('servicios/periodoncia', periodoncia, name='periodoncia'),
    path('servicios/protesis-removibles', protesisRemovibles, name='protesisRemovibles'),
    path('servicios/tratamiento-de-caries', tratamientoDeCaries, name='tratamientoDeCaries'),
    path('servicios/tratamiento-de-conducto', tratamientoDeConducto, name='tratamientoDeConducto'),
    path('servicios/evaluacion-radiografica', evaluacionRadiografica, name='evaluacionRadiografica'),
    path('servicios/coronas-y-puentes', coronasYPuentes, name='coronasYPuentes'),
    path('sobre-nosotros', sobreNosotros, name='sobreNosotros'),
    path('contactos', contactos, name='contactos'),
    path('procesar-mensaje', procesarMensaje, name='procesarMensaje'),
    path('login', login, name='login'),
    path('registrar-usuario', registrarUsuario, name='registrarUsuario'),
    path('procesar-login', procesarLogin, name='procesarLogin'),
    path('logout', logout, name='logout'),
    path('solicitar-cita', solicitarCita, name='solicitarCita'),
    path('procesar-cita', procesarCita, name='procesarCita'),
    path('administrar-doctores', administrarDoctores, name='administrarDoctores'),
    path('agregar-doctor', agregarDoctor, name='agregarDoctor'),
    path('registrar-doctor', registrarDoctor, name='registrarDoctor'),
    path('actualizar-doctor/<int:ci_doctor>', actualizarDoctor, name='actualizarDoctor'),
    path('cambiar-doctor', cambiarDoctor, name='cambiarDoctor'),
    path('despedir-doctor/<int:ci_doctor>', despedirDoctor, name='despedirDoctor'),
    path('administrar-citas', administrarCitas, name='administrarCitas'),
    path('aceptar-cita/<int:id_cita>', aceptarCita, name='aceptarCita'),
    path('rechazar-cita/<int:id_cita>', rechazarCita, name='rechazarCita'),
    path('modificar-cita-aceptada/<int:id_cita>', modificarCitaAceptada, name='modificarCitaAceptada'),
    path('cambiar-cita-aceptada', cambiarCitaAceptada, name='cambiarCitaAceptada'),
    path('quitar-cita-aceptada/<int:id_cita>', quitarCitaAceptada, name='quitarCitaAceptada'),
    path('quitar-cita-rechazada/<int:id_cita>', quitarCitaRechazada, name='quitarCitaRechazada'),
    path('ver-cita/<int:id_cita>', verCita, name='verCita'),
    path('ver-cliente/<int:ci_cliente>', verCliente, name='verCliente'),
    path('ver-doctor/<int:ci_doctor>', verDoctor, name='verDoctor'),
]